name: 'Runtime Analyzer'
description: 'Setup Kubescape runtime analysis environment and perform dynamic security analysis'
inputs:
  action:
    description: 'Action to perform (setup-cluster, deploy-and-analyze, cleanup)'
    required: true
  cluster-name:
    description: 'Kubernetes cluster name'
    required: false
    default: 'security-analysis-cluster'
  image-ref:
    description: 'Container image reference to analyze'
    required: false
  app-name:
    description: 'Application name for deployment'
    required: false
  timeout:
    description: 'Timeout for operations in seconds'
    required: false
    default: '600'
  vex-analysis-time:
    description: 'VEX analysis duration (e.g., "2m", "5m", "10m")'
    required: false
    default: '2m'
  use-external-cluster:
    description: 'Whether to use external cluster (true/false)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Runtime Analysis Operations
      shell: bash
      run: |
        # Set up environment variables for scripts
        export CLUSTER_NAME="${{ inputs.cluster-name }}"
        export USE_EXTERNAL_CLUSTER="${{ inputs.use-external-cluster }}"
        export VEX_ANALYSIS_TIME="${{ inputs.vex-analysis-time }}"
        export TIMEOUT="${{ inputs.timeout }}"
        export IMAGE_REF="${{ inputs.image-ref }}"
        export APP_NAME="${{ inputs.app-name }}"
        
        # Get the directory of this action
        ACTION_DIR="${{ github.action_path }}"
        
        case "${{ inputs.action }}" in
          "setup-cluster")
            bash "$ACTION_DIR/scripts/setup-cluster.sh"
            ;;
          "deploy-and-analyze")
            bash "$ACTION_DIR/scripts/deploy-and-analyze.sh"
            ;;
          "cleanup")
            bash "$ACTION_DIR/scripts/cleanup.sh"
            ;;
          *)
            echo "❌ Unknown action: ${{ inputs.action }}"
            exit 1
            ;;
        esac
